### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by fjallraven** [unity3d-jp/AlembicImporter#4]
Hello
I'm trying to get this building on linux but getting stuck

Any plans of supporting linux?

Thank you

> In file included from /Importer/aiContext.cpp:4:0:
> /Importer/aiContext.h: In member function ‘void aiContext::eachNodes(const F&)’:
> /Importer/aiContext.h:79:19: error: invalid use of incomplete type ‘class aiObject’
>          m_top_node->eachChildrenRecursive(f);
>                    ^
> In file included from /Importer/aiContext.cpp:2:0:
> /Importer/AlembicImporter.h:89:9: error: forward declaration of ‘class aiObject’
>  class   aiObject;
>          ^
> /Importer/aiContext.cpp: In member function ‘void aiContext::gatherNodesRecursive(aiObject*)’:
> /Importer/aiContext.cpp:331:54: error: no matching function for call to ‘aiObject::newChild(Alembic::Abc::v7::IObject)’
>          aiObject *child = n->newChild(abc.getChild(i));

**Comment by fjallraven** [comment]
With the recent build changes it's almost there.

> In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /alembic_importer/Plugin/./abci/pch.h:1,
                 from /alembic_importer/Plugin/abci/Importer/aiSchema.cpp:1:
/usr/include/c++/4.8.2/bits/stl_algo.h: In instantiation of â€˜_RandomAccessIterator std::__unguarded_partition(_RandomAccessIterator, _RandomAccessIterator, const _Tp&, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<std::unique_ptr<aiProperty>*, std::vector<std::unique_ptr<aiProperty> > >; _Tp = std::unique_ptr<aiProperty>; _Compare = aiSchemaBase::setupProperties()::__lambda3]â€™:
/usr/include/c++/4.8.2/bits/stl_algo.h:2296:78:   required from â€˜_RandomAccessIterator std::__unguarded_partition_pivot(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<std::unique_ptr<aiProperty>*, std::vector<std::unique_ptr<aiProperty> > >; _Compare = aiSchemaBase::setupProperties()::__lambda3]â€™
/usr/include/c++/4.8.2/bits/stl_algo.h:2337:62:   required from â€˜void std::__introsort_loop(_RandomAccessIterator, _RandomAccessIterator, _Size, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<std::unique_ptr<aiProperty>*, std::vector<std::unique_ptr<aiProperty> > >; _Size = long int; _Compare = aiSchemaBase::setupProperties()::__lambda3]â€™
/usr/include/c++/4.8.2/bits/stl_algo.h:5499:44:   required from â€˜void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = __gnu_cxx::__normal_iterator<std::unique_ptr<aiProperty>*, std::vector<std::unique_ptr<aiProperty> > >; _Compare = aiSchemaBase::setupProperties()::__lambda3]â€™
/alembic_importer/Plugin/abci/Importer/aiSchema.cpp:147:87:   required from here
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: error: no match for call to â€˜(aiSchemaBase::setupProperties()::__lambda3) (std::unique_ptr<aiProperty>&, const std::unique_ptr<aiProperty>&)â€™
    while (__comp(*__first, __pivot))
                                   ^
/alembic_importer/Plugin/abci/Importer/aiSchema.cpp:147:10: note: candidates are:
         [](aiPropertyPtr& a, aiPropertyPtr& b) { return a->getName() < b->getName(); });
          ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /alembic_importer/Plugin/./abci/pch.h:1,
                 from /alembic_importer/Plugin/abci/Importer/aiSchema.cpp:1:
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: note: bool (*)(aiSchemaBase::aiPropertyPtr&, aiSchemaBase::aiPropertyPtr&) {aka bool (*)(std::unique_ptr<aiProperty>&, std::unique_ptr<aiProperty>&)} <conversion>
    while (__comp(*__first, __pivot))
                                   ^
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: note:   candidate expects 3 arguments, 3 provided
/alembic_importer/Plugin/abci/Importer/aiSchema.cpp:147:46: note: aiSchemaBase::setupProperties()::__lambda3
         [](aiPropertyPtr& a, aiPropertyPtr& b) { return a->getName() < b->getName(); });
                                              ^
/alembic_importer/Plugin/abci/Importer/aiSchema.cpp:147:46: note:   no known conversion for argument 2 from â€˜const std::unique_ptr<aiProperty>â€™ to â€˜aiSchemaBase::aiPropertyPtr& {aka std::unique_ptr<aiProperty>&}â€™
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /alembic_importer/Plugin/./abci/pch.h:1,
                 from /alembic_importer/Plugin/abci/Importer/aiSchema.cpp:1:
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: error: no match for call to â€˜(aiSchemaBase::setupProperties()::__lambda3) (const std::unique_ptr<aiProperty>&, std::unique_ptr<aiProperty>&)â€™
    while (__comp(__pivot, *__last))
                                  ^
/alembic_importer/Plugin/abci/Importer/aiSchema.cpp:147:10: note: candidates are:
         [](aiPropertyPtr& a, aiPropertyPtr& b) { return a->getName() < b->getName(); });
          ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /alembic_importer/Plugin/./abci/pch.h:1,
                 from /alembic_importer/Plugin/abci/Importer/aiSchema.cpp:1:
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: note: bool (*)(aiSchemaBase::aiPropertyPtr&, aiSchemaBase::aiPropertyPtr&) {aka bool (*)(std::unique_ptr<aiProperty>&, std::unique_ptr<aiProperty>&)} <conversion>
    while (__comp(__pivot, *__last))
                                  ^
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: note:   candidate expects 3 arguments, 3 provided
/alembic_importer/Plugin/abci/Importer/aiSchema.cpp:147:46: note: aiSchemaBase::setupProperties()::__lambda3
         [](aiPropertyPtr& a, aiPropertyPtr& b) { return a->getName() < b->getName(); });
                                              ^
/alembic_importer/Plugin/abci/Importer/aiSchema.cpp:147:46: note:   no known conversion for argument 1 from â€˜const std::unique_ptr<aiProperty>â€™ to â€˜aiSchemaBase::aiPropertyPtr& {aka std::unique_ptr<aiProperty>&}â€™

**Comment by i-saint** [comment]
it is already working on Ubuntu ( gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ).
I committed possible fix ( https://github.com/unity3d-jp/AlembicImporter/commit/1d3efbbc1abc261550980a04541933e3c416b1ed ), but I can't confirm.

**Comment by fjallraven** [comment]
Many thanks, that works well!
